### ISSUE TITLE
ExtentITestListenerClassAdapter throws error

### ISSUE THREAD

**Issue by sseenivasan89** [extent-framework/extentreports-testng-adapter#14]
I have added ExtentITestListenerClassAdapter listener (below line) to my testng-xml suite file and when i ran got error (last line)
listener class-name="com.aventstack.extentreports.adapter.listener.ExtentITestListenerClassAdapter"
i just added extentreports-testng-adapter dependency to pom file and placed both extent.properties and config.xm file in src/test/resources folder, am i missing anything ?

`**Error : Listener com.aventstack.extentreports.adapter.listener.ExtentITestListenerClassAdapter was not found in project's classpath**`

**Comment by anshooarora** [comment]
@sseenivasan89 Can you create a small repo and share?  There is an example [here](https://github.com/extent-framework/extentreports-testng-adapter/blob/master/src/test/resources/com/aventstack/adapter/ireporter-suite1.xml) which you can refer to as well.

**Comment by sseenivasan89** [comment]
Hi Sir,
i was able to get report when i run test from class file since i used @Listeners in class file, but if i add @Listeners in testng.xml file and try to run, getting below error and here is the [repo](https://github.com/sseenivasan89/TestNG-Extent) which i tried 

***Error : Listener Extent.Adapter.ExtentIReporterSuiteClassAdapter was not found in project's classpath***

**Comment by anshooarora** [comment]
Thanks for pointing this one out,  I was able to reproduce and the path to the listener was invalid.  You can use any one of below (with the correct package name):

```
<listeners>
  <listener class-name="com.aventstack.extentreports.testng.listener.ExtentITestListenerClassAdapter" />
</listeners>

<listeners>
  <listener class-name="com.aventstack.extentreports.testng.listener.ExtentITestListenerAdapter" />
</listeners>

<listeners>
  <listener class-name="com.aventstack.extentreports.testng.listener.ExtentIReporterSuiteClassListenerAdapter" />
</listeners>

<listeners>
  <listener class-name="com.aventstack.extentreports.testng.listener.ExtentIReporterSuiteListenerAdapter" />
</listeners>
```

**Comment by sseenivasan89** [comment]
Thanks @anshooarora sir now i able to run successfully 👍
