### ISSUE TITLE
Update to extentreports 5.0.0 and now the adapter 1.0.7 doesn't work

### ISSUE THREAD

**Issue by lgarelli-thefork** [extent-framework/extentreports-testng-adapter#15]
Hello, our dependabot updated extentreports to 5.0.0 and now when using the testng adapter version 1.0.7, no tests are found by testng. If I remove the @Listeners({ExtentITestListenerAdapter.class}) annotation then the tests are found (but no report generated)

Is this a known issue? Incompatibility between adapter version 1.0.7 and extent reports 5.0.0 ?

**Comment by anshooarora** [comment]
The plugin version 1.0.7 does not support the latest ExtentReports release.  I would suggest to roll-back to 4.1.x series. 

Version 5 will be supported by https://github.com/extent-framework/extentreports-testng-adapter/tree/v1.2.x to launch very soon.

**Comment by lgarelli-thefork** [comment]
Thanks @anshooarora !
