### ISSUE TITLE
TestName is not correctly set when using @beforeMethod annotation in ExtentITestListenerAdapter

### ISSUE THREAD

**Issue by lgarelli-thefork** [extent-framework/extentreports-testng-adapter#17]
Hello,

I just updated to ExtentReports 5.0.0 and extentreports-testng-adapter 1.2.0. After updating I noticed a big change in behaviour in the ExtentITestListenerAdapter. 

Previously, the name of the test was set correctly to the left of the report as can be seen in the following image:

![image](https://user-images.githubusercontent.com/57663587/88463843-26e2f800-ceb6-11ea-8ac1-039fe55bad88.png)

After updating to the latest version, now the name of the before method is the one written to the left (it's repeated 10 times because I'm using 10 parallel threads).

![image](https://user-images.githubusercontent.com/57663587/88463844-2a767f00-ceb6-11ea-981d-1e9e1f492862.png)

I saw in #5 that this was done to avoid a NPE, however I think that the expected behaviour when using the ExtentITestListenerAdapter should be to have the name of the test method at the left of the report (as it was until the version 1.0.7) and not the name of the "beforeMethod" method as now in version 1.2.0.

Is there a way to write the name of the test on the left when using a @beforeMethod annotation and ExtentITestListenerAdapter ?

Is there a way to skip this createMethod here?

```java
    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        if (method.getTestMethod().isBeforeMethodConfiguration()) {
            createdMethodBeforeInvocation = true;
            ExtentTestManager.createMethod(testResult);
        }
    }

**Comment by anshooarora** [comment]
@lgarelli-thefork This change should not have been merged. 

Please check with `1.2.1-SNAPSHOT`.  [linky](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports-testng-adapter/1.2.1-SNAPSHOT/)

**Comment by lgarelli-thefork** [comment]
Thanks for your prompt response @anshooarora ! Well, I can wait for the official 1.2.1. Any possible release date?

**Comment by anshooarora** [comment]
Since this change reverts back to the original code, I can release in the next few mins.  Can you confirm this reverts back to the pre-#5 view?

**Comment by lgarelli-thefork** [comment]
@anshooarora it works!

![image](https://user-images.githubusercontent.com/57663587/88464432-f81b5080-ceba-11ea-8c6e-b3c760fdb456.png)

**Comment by anshooarora** [comment]
Awesome, thanks!  Pushing release to nexus now.

**Comment by anshooarora** [comment]
Its live now https://oss.sonatype.org/#nexus-search;quick~extentreports-testng.  Generally takes a few hours to reflect on mvnrepository/search.maven.  Cheers

**Comment by lgarelli-thefork** [comment]
thanks a lot!
