### ISSUE TITLE
SKIP Exception if used in @BeforeSuite - throws null pointer exception

### ISSUE THREAD

**Issue by sen1983** [extent-framework/extentreports-testng-adapter#2]
[LearnTestNG.zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2666285/LearnTestNG.zip)

If we use SKIP Exception in the @BeforeSuite then ITestListener throws null pointer exception, also all the test skips and executed(failed), so we can see the entry as Test1 (skipped) and Test1(Failed).

**Comment by anshooarora** [comment]
@sen1983  thank you, I am able to reproduce.

**Comment by sen1983** [comment]
Hi Anshoo,

Still we are getting the same issue, Please include @BeforeSuite with Skip Exception in Class1 and when executed throws null pointer exception.
[extentreports-testng-adapter-master.zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2671449/extentreports-testng-adapter-master.zip)

![exception](https://user-images.githubusercontent.com/45349008/49862642-9eb8f780-fe24-11e8-836c-ed7532c48213.JPG)

**Comment by anshooarora** [comment]
Ok, so the same issue within `onTestFailure`.  What baffles me is that `getThrowable()` is null on both skipped and failure.  I will push the fix in a few mins.

**Comment by sen1983** [comment]
Hi Anshoo,

I was the facing the same exception again but later identified the root cause. Actually I am using TestNG 6.14.3 eclipse plugin. Then I have downgraded the TestNG version to 6.9.10 and it is working fine.

Could you please fix the same for the latest version of the TestNG 6.14.3?

Thanks
Senthil

**Comment by anshooarora** [comment]
I am unable to reproduce using `testng:6.14.3` with the last commit.

**Comment by sen1983** [comment]
Hi Anshoo,

Its not working, believe me still this issue exists with ITestListener. Attached the project below i have included only ITestListener listener alone for testing.

[TestNGAdapter.zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2678856/TestNGAdapter.zip)

I have just added Skip exception in beforesuite and a new test for skip exception.
Please check it and let me know if anything I did wrong in the code.

**Comment by anshooarora** [comment]
Please try with the attached:

[TestNGAdapter.zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2687013/TestNGAdapter.zip)

**Comment by sen1983** [comment]
Thanks for the update, now its executing fine, but the report is incorrect, so raising new issue.
