### ISSUE TITLE
Extent Report is incorrect if ITestListener is used

### ISSUE THREAD

**Issue by sen1983** [extent-framework/extentreports-testng-adapter#3]
Hi Anshoo,

Report shows only one test case with exceptions, please find attached the screenshot for more details.

![eclipse_output](https://user-images.githubusercontent.com/45349008/50141909-b7b32400-02ce-11e9-901c-d69fa2d29b80.JPG)
![extentrpt1](https://user-images.githubusercontent.com/45349008/50141916-bbdf4180-02ce-11e9-80e2-7c308c77872c.JPG)
![extentrpt2](https://user-images.githubusercontent.com/45349008/50141928-c00b5f00-02ce-11e9-9bd8-a4dde74366ea.JPG)

Thanks
Sen

**Comment by anshooarora** [comment]
Can you share an example for me to repro?

**Comment by sen1983** [comment]
[TestNGAdapter (2).zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2713841/TestNGAdapter.2.zip)

Please find attached the example.

**Comment by sen1983** [comment]
Hi Anshoo,

Wish u happy New Year!!!..

Did you get a chance to look at the file that is attached in the previous post?

Thanks
Sen

**Comment by anshooarora** [comment]
Happy new year!

I will check this tomorrow,  thank you for your patience.

**Comment by anshooarora** [comment]
Please check with `1.0.3`, it was fixed earlier.  The code in your repo is from an older commit.

**Comment by anshooarora** [comment]
Still unable to reproduce, here is what I am seeing:

[ExtentHtml.zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2762610/ExtentHtml.zip)

**Comment by sen1983** [comment]
Did you skip the beforesuite? if its skipped at beforesuite then we see the report incorrect. Could you please share me the sample code that you verified

**Comment by sen1983** [comment]
Hi Anshoo,

Did you get a chance to look into my comments?

Thanks
Sen

**Comment by anshooarora** [comment]
I will look into this today..

**Comment by sen1983** [comment]
Hi Anshoo,

Able to reproduce this issue?, if we skip the before suite we do see this incorrect report.

Thanks
Sen

**Comment by anshooarora** [comment]
I am really not sure what is happening.  I run your class in your project and I get these errors.  Running them directly in mine creates the correct report.

**Comment by anshooarora** [comment]
What timezone are you in?  We can do a quick Webex.  See the report that was just created.

[ExtentHtml.zip](https://github.com/extent-framework/extentreports-testng-adapter/files/2830318/ExtentHtml.zip)

**Comment by sen1983** [comment]
Thanks for the quick update... 

I am in IST zone, let me know your convenient time so that we can do webex. 

Did you skip the beforsuite? report comes incorrect only when we skip the before suite.

Thanks
Sen

**Comment by anshooarora** [comment]
Yes, this is after skipping the beforesuite.

**Comment by sen1983** [comment]
Still no luck for me.. let me know your convenient time to do webex... Pls share the webex link

**Comment by sen1983** [comment]
Did you get a chance to find why these error is coming?.. Is anything I am missing?/to update any jars or code difference?

Please let me know.

Thanks
Senthil Raj R

**Comment by sen1983** [comment]
I just downloaded the source and import it in to eclipse, I didn't do any changes. 

Could you please help me to resolve this?

Thanks
Sen
