### ISSUE TITLE
Info(msg) is not working in before method/class

### ISSUE THREAD

**Issue by Rahul-QA** [extent-framework/extentreports-testng-adapter#5]
Hi Anshoo,

I am getting nullpointer exception for using info in @beforemethod

ExtentTestManager.getTest().info("inside beforeMethod");

![beforemethod](https://user-images.githubusercontent.com/12069520/63006315-e3a59a00-be9b-11e9-81cf-56d93ee3c694.PNG)

**Comment by anshooarora** [comment]
Which listener? Complete stacktrace?

**Comment by Ashwini1980** [comment]
Hi,

I am also getting null pointer exceptions while using ExtentTestManager.getTest().info("inside beforeMethod");.

I am using the ExtentITestListenerClassAdapter class.

Code:

public class Test4 {
	
	WebDriver driver;

    @BeforeSuite
    public void setUp() {
    	
    	ExtentService.getInstance().setSystemInfo("Dev Name", "Ashwin Pattanayak");
    	ExtentService.getInstance().setSystemInfo("Broser Name", "Chrome");
    	ExtentService.getInstance().setSystemInfo("OS", "WINDOWS 10");
    }
    
    @BeforeMethod
    public void login() {
    	
		System.setProperty("webdriver.chrome.driver", 
 System.getProperty("user.dir")+"/src/test/resources/executables/chromedriver.exe");
		driver = new ChromeDriver();
		System.out.println("Launching Chrome driver");
		ExtentTestManager.getTest().info("Launching Chrome driver");
    }
    
    @Test
    public void getTitle() {
    	
    	ExtentTestManager.getTest().info("Test Execution started.");
    	driver.get("https://www.google.com");
    	String title = driver.getTitle();
    	System.out.println("Title is: "+title);
    }

Exception:

![image](https://user-images.githubusercontent.com/30127144/80672279-e697f780-8ac9-11ea-9ecf-cddf6f8ed76a.png)

It seems the problem is while creating the method on the listener clas:
 ExtentTestManager.createMethod(result, true);

Please correct me if I am wrong. Please give us a solution please so that we will not get null pointer exception.

**Comment by Ashwini1980** [comment]
> Hi Anshoo,
> 
> I am getting nullpointer exception for using info in @beforemethod
> 
> ExtentTestManager.getTest().info("inside beforeMethod");
> 
> ![beforemethod](https://user-images.githubusercontent.com/12069520/63006315-e3a59a00-be9b-11e9-81cf-56d93ee3c694.PNG)

Hi Rahul..

Were you able to resolve this issue?

**Comment by Ashwini1980** [comment]
Hi Anshoo,

Can you please guide me where I went wrong?
Should We do something onStart method in the listener class?

**Comment by anshooarora** [comment]
@Ashwini1980 This is because the test is not created yet, it gets created when `onTestStart` executes which is why you are getting a NPE in your BeforeMethod.

**Comment by anshooarora** [comment]
I have attempted to fix this,  please test using version `1.0.8-SNAPSHOT`. [link](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports-testng-adapter/)

```
<groupId>com.aventstack</groupId>
<artifactId>extentreports-testng-adapter</artifactId>
<version>1.0.8-SNAPSHOT</version>
```

**Comment by Ashwini1980** [comment]
I tried with the maven and seems artifact is missing and I am getting:
![image](https://user-images.githubusercontent.com/30127144/80907985-55c75300-8d39-11ea-938d-215f6bc725ab.png)

Hence I download the JAR file manually and add it to the Java build path but still I am facing the same issue i.e. getting null pointer exception:

![image](https://user-images.githubusercontent.com/30127144/80908037-09304780-8d3a-11ea-9e9a-7f851bcaf140.png)

![image](https://user-images.githubusercontent.com/30127144/80908046-236a2580-8d3a-11ea-95c5-a6be98f6468b.png)

**Comment by anshooarora** [comment]
You

**Comment by Ashwini1980** [comment]
Thanks. Now no errors on pom.xml now. But earlier as I mentioned still getting null pointer exceptions.

**Comment by Ashwini1980** [comment]
Hi Anshoo,

Did you get a chance to look into this issue?

Thanks,
Ashwin

**Comment by anshooarora** [comment]
Can you share a small project which reproduces this?  I am unable to on my end..  thank you.

**Comment by Ashwini1980** [comment]
https://github.com/Ashwini1980/Repo4/tree/master/ExtentReportIssue

**Comment by Ashwini1980** [comment]
Another observation. I upgraded to latest  version i.e. 4.1.5. (Earlier I used to use 4.0.9 where I was getting nullpointer exception) Now I am not getting null pointer exceptions when I am using ExtentTestManager.getTest().info("Launching Chrome driver") @BeforeMethod. But Now I am getting null pointer exception while flushing the extent report:

![image](https://user-images.githubusercontent.com/30127144/82129369-d8431e80-97df-11ea-8303-06444bbf4f24.png)

![image](https://user-images.githubusercontent.com/30127144/82129379-ea24c180-97df-11ea-9ad1-1671d8949d4f.png)

**Comment by anshooarora** [comment]
Thanks, checking now.

**Comment by anshooarora** [comment]
You are not using the adapter:  https://github.com/Ashwini1980/Repo4/blob/master/ExtentReportIssue/pom.xml

Is this an issue you are experiencing with the adapter or ExtentReports?

**Comment by Ashwini1980** [comment]
Sorry for the confusion.
Please use https://github.com/Ashwini1980/Repo5.git

Note: It seems beforeMethod is working fine but beforeTest and BeforeSuite is not working. For beforeTest and suite still I am getting null pointer exceptions.

**Comment by Ashwini1980** [comment]
Hi Anshoo,

Did you get a chance to look into this?
Still @beforeTest and @BeforeSuite is throwing null pointer exceptions while using ExtentTestManager.getTest().info("").

**Comment by Ashwini1980** [comment]
Hi Anshoo,

Did you get a chance to look into this?

Thanks

**Comment by Ashwini1980** [comment]
Hi Anshoo,

Did you get a chance to look into this?

Thanks

**Comment by anshooarora** [comment]
@Ashwini1980 I looked at your repo, and it seems to me you want to mix custom implementation with the listener. That may not be straight-forward, if even possible.  The listener is meant to be used as-is without any custom logging, by letting the listener do the job of reporting.  I have sent you a pull request to show the intended usage - please check.

**Comment by Ashwini1980** [comment]
Thanks Anshoo.
I got the usage details. But I am trying to automate the following scenarios:

Scenario: 
In the before suite, I want to login to a URL and in the Extent report I want to show login was successful.
Ex: ExtentTestManager.getTest().pass(Before suite started...");
     ExtentTestManager.getTest().pass("Login to URL was successful.");

In the Before test/class, I want to download a file after login and in the Extent report I want to show File download was successful.
Ex: ExtentTestManager.getTest().pass(Before Test/Class started...");
    ExtentTestManager.getTest().pass("File download was successful.");

In Before Method, I want to do something with the download file and start the test case.
Ex: ExtentTestManager.getTest().pass("Started Amazon service.");
     ExtentTestManager.getTest().pass("Test Execution started.");
So in the final report it show all the logging as mentioned above.

Can I do the same by using extentreports-testng-adapter alone? I tried and it did not work and getting same null pointer exception as mentioned in the original thread. If we can do it by using this testNg adapter please let me know.

As this did not work, hence I mixed custom implementation with the listener and tried to do it.

		+ the TestNG Lister

In the above version, If I am trying to do logging on @BeforeMethod and @test and @after..., it is working fine. But while doing with @BeforeSuite, @Beforetest and @Beforeclass, it is throwing same null pointer exception. I think it is expected as we are trying to initialize the create method during onTestStart or beforeInvocation method as follows:
ExtentTestManager.createMethod(result);

As you mentioned it is very straight forward to implement with custom implementation, is there any other way to get the Extent report with all the logging(as mention in the above mentioned scenarios)?

Thank in Advance!!

Regards,
Ashwini

**Comment by anshooarora** [comment]
@Ashwini1980 What you are trying to do cannot be achieved directly by the adapter as it will use the pre-defined logic to build the report.  You would need to create a custom implementation to achieve the desired behavior..
