### ISSUE TITLE
testng-adapter picking up the old version of the extent reports from mvn repo.

### ISSUE THREAD

**Issue by arkkgit** [extent-framework/extentreports-testng-adapter#6]
Hi,
I can see  the new POM of extentreports-testng-adapter is been updated with the latest extent reports ver 4.0.9. when used from the mvn repo its still picking up the old version 4.0.6 Please see the screenshot.

Many Thanks,

![image](https://user-images.githubusercontent.com/52240959/68650858-02bfd080-054c-11ea-9f54-b7f77a907e9a.png)

**Comment by anshooarora** [comment]
In case you are still having this issue, I would suggest:

1. Doing a rebuild of project so maven can download all dependencies
2. Excluding extentreports dependency from the adapter and explicitly using 4.0.9
