### ISSUE TITLE
Printing Test class description

### ISSUE THREAD

**Issue by PrasadKhandekar** [extent-framework/extentreports-testng-adapter#7]
Hello,

I have noticed that the description provided on the Test annotation at the class level does not get printed in the HTML report. It will be really nice if its gets printed in the report as well just below the `<h5 class='test-name'></h5>` element (`v3-html-test-view.ftl`).

Looked at the `ExtentTestManager.java` & feel that the method  `createTest(ITestResult result, ExtentTest classTest)' needs some modifications.

**Comment by anshooarora** [comment]
@PrasadKhandekar can you check with the latest snapshot:

```
<groupId>com.aventstack</groupId>
<artifactId>extentreports-testng-adapter</artifactId>
<version>1.0.4-SNAPSHOT</version>
```

**Comment by PrasadKhandekar** [comment]
Thank you Ansho for fixing the issue. I will revert back after checking it today!
